server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Povolení vložení přes iframe z jakékoli domény
    add_header X-Frame-Options "";
    add_header Content-Security-Policy "frame-ancestors *";

    location /api/ {
        proxy_pass http://api:3001/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}
